### ISSUE TITLE
Problem installing bundler when capistrano-bundler enabled

### ISSUE THREAD

**Issue by jimmynguyc** [capistrano-plugins/capistrano-rbenv-install#2]
Capistrano-bundler prefixes the gem command with "bundle exec". Which makes the rbenv:install_bundler command to run like this

`bundle exec gem install bundler`

**Comment by jimmynguyc** [comment]
Made a pull request https://github.com/capistrano-plugins/capistrano-rbenv-install/pull/1

**Comment by bruno-** [comment]
Hi, thank you for taking the time to report this issue and work on implementing a fix.

I just tested this by deploying to a new server.  Here are the files I'm requiring in Capfile:

``` ruby
# Capfile
require 'capistrano/rbenv'
require 'capistrano/rbenv_install'
require 'capistrano/bundler'
require 'capistrano/rails'
...
```

and here are the commands that got executed:

```
[45112a69] Running ~/.rbenv/bin/rbenv exec gem query --quiet --installed --name-matches ^bundler$
....
[fc1c9f38] Running ~/.rbenv/bin/rbenv exec gem install bundler --quiet --no-rdoc --no-ri
```

Basically everything went fine with this try..

I tried switching capistrano-bundler and capistrano-rbenv positions in `Capfile` (and also changed ruby version so a fresh version is installed):

``` ruby
# Capfile
require 'capistrano/bundler' # this before requiring rbenv
require 'capistrano/rbenv'
require 'capistrano/rbenv_install'
```

And bingo, now things broke apart with this in the log:

```
[b1561eaa] Running ~/.rbenv/bin/rbenv exec bundle exec gem query --quiet --installed --name-matches ^bundler$
```

Anyway, I investigated this for a while and I think I figured the problem (the least the above scenario was successful).
Here's the fix implementation: https://github.com/capistrano-plugins/capistrano-rbenv-install/commit/e1c0bfc51d9d5fba7d71c1fd453a59b5118c7ee1

Also, I pushed a new gem version: `v1.1.0`. Can you please try this and let me know if it's working for you too?

Thanks!

**Comment by jimmynguyc** [comment]
Works !!! :) thanks @bruno-

**Comment by bruno-** [comment]
Awesome :+1:
