### ISSUE TITLE
Update ruby-build plugin before running rbenv:install_ruby

### ISSUE THREAD

**Issue by jimmynguyc** [capistrano-plugins/capistrano-rbenv-install#3]
Would be nice to have `ruby-build` updated before running `rbenv install`. 

Otherwise installing latest ruby releases would usually fail with 

``` bash
SSHKit::Command::Failed: ~/.rbenv/bin/rbenv exit status: 2
~/.rbenv/bin/rbenv stdout: Nothing written
~/.rbenv/bin/rbenv stderr: ruby-build: definition not found: 1.9.3-p551

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  cd /home/mvdev/.rbenv/plugins/ruby-build && git pull
```

**Comment by jimmynguyc** [comment]
Made it work on my fork with this chunk of code ... 

https://github.com/jimmynguyc/capistrano-rbenv-install/blob/335a0a0cf5255a03e2e5525a3cf5a058985561b1/lib/capistrano/tasks/rbenv_install.rake#L30-L36

**Comment by bruno-** [comment]
Looks like a nice feature when a user want to "ride" the latest ruby version.
Feel free to open a pull request :+1:

**Comment by jimmynguyc** [comment]
Here you go :)

https://github.com/capistrano-plugins/capistrano-rbenv-install/pull/4
