### ISSUE TITLE
update ruby-build?

### ISSUE THREAD

**Issue by ened** [capistrano-plugins/capistrano-rbenv-install#5]
Hi!

Thanks for the nice plugin.
Does it actually update the ruby-build plugin (`cd $RBENV_HOME/plugins/ruby-build && git pull`) before trying to install a new ruby version?

Sebastian

**Comment by bruno-** [comment]
Yep. That was a recent contribution by @jimmynguyc.
If you're interested, the relevant task in the source is [here](https://github.com/capistrano-plugins/capistrano-rbenv-install/blob/master/lib/capistrano/tasks/rbenv_install.rake#L30-L38).

**Comment by ened** [comment]
Thanks @bruno- - I will test it again once Ruby 2.1.6 is released.
